apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildcard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wildcard
  template:
    metadata:
      labels:
        app: widlcard
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer